### ISSUE TITLE
ttl - second vs minute

### ISSUE THREAD

**Issue by subdesign** [slakbal/gotowebinar#11]
In Laravel 5.5 cache ttl is set in `minutes` and in the latest code `seconds` is used, any chance for a config setting for ttl, or other solution?
```php
private function setAccessToken($accessToken, $ttlSeconds = null)
{
    Cache::tags($this->cache_tags)->put('access-token', $accessToken, $ttlSeconds ?? Carbon::now()->addHour());
     return $this;
}
```
We can't update right now the project to L5.8+ because it's so huge not feasible

thanks

**Comment by slakbal** [comment]
Hmmm, don't want to create a separate branch... and the value is also dynamically set on responses from the Goto API which also is in seconds. Laravel was the culprit here when then had the ttl in minutes :)

For example:

```php
private function refreshAccessToken()
    {
        $response = $this->sendAuthenticationRequest([
                                                         'grant_type' => 'refresh_token',
                                                         'refresh_token' => $this->getRefreshToken(),
                                                     ]);

        $this->setAccessToken($response->access_token, $response->expires_in);

        return $response;
    }
``` 

Any ideas on how we can have both worlds in there?

**Comment by subdesign** [comment]
Our recommendation:

Modify the following method in the trait `Slakbal\Gotowebinar\Client\AccessProvider`

```php
private function setAccessToken($accessToken, $ttlSeconds = null)
{
    Cache::tags($this->cache_tags)->put('access-token', $accessToken, $ttlSeconds 
        ? Carbon::now()->addSeconds($ttlSeconds) 
        : Carbon::now()->addHour()
    );
    
    return $this;
}
```
same approach works with `setRefreshToken`

**Comment by slakbal** [comment]
Hi @subdesign 

Sorry for the late reply. Is this still required, or can it be closed?

Thanks!

**Comment by wize-wiz** [comment]
This can be closed, minutes to seconds was a breaking change in Laravel anyway. 6.x is the LTS, not 5.x.
