### ISSUE TITLE
Bad Request (400)

### ISSUE THREAD

**Issue by prg-hussam** [slakbal/gotowebinar#5]
received this error when create a webinar
![screenshot from 2018-11-24 14-37-59](https://user-images.githubusercontent.com/18707331/48968330-9aa07380-eff6-11e8-9226-d31650deeb99.png)

**Comment by slakbal** [comment]
Sorry for the delayed reply. Did you get sorted on this?

**Comment by domioanna** [comment]
I had this same issue, but I worked out that it was because I was creating a webinar for a past date / time.  It will only accept dates and times that are in the future (obviously).

**Comment by slakbal** [comment]
@domioanna thanks for the feedback. I can confirm everything works well on my side. @prg-hussam make sure that you are passing in data as expected by GotoWebinar. I'm working on the new release and will see if I can add in better error logging to help with integration issues.
