### ISSUE TITLE
Client authentication failed

### ISSUE THREAD

**Issue by GalBrigitta** [slakbal/gotowebinar#7]
```
array:2 [
  "state" => "Access object available"
  "accessObject" => {#278 
    +"error": "invalid_client"
    +"error_description": "Client authentication failed."
  }
]
```
I get this error in browser after this in my controller:
```
     $gotoResponse = GotoWebinar::state(false);
        dd($gotoResponse);
```
I guess I did not set up something, but I did as I read in the doc.  So I got this package in my laravel project, I've made an app in goto-developer page. I got the keys and I put in into my .env file like this, but with my real datas.
```
GOTO_DIRECT_USER=
GOTO_CONSUMER_SECRET=
GOTO_CONSUMER_KEY=
```

**Comment by upwebdesign** [comment]
@GalBrigitta are you still getting this error?

**Comment by GalBrigitta** [comment]
@upwebdesign yes. I haven't worked with this after. But I need to implement it soon.. I hope I can figure out.

**Comment by upwebdesign** [comment]
@GalBrigitta my gut feeling is a permissions issue or a cache issue.

**Comment by GalBrigitta** [comment]
I have already cleared the cache. How can it be a permission issue?

**Comment by upwebdesign** [comment]
@GalBrigitta what are you using for `CACHE_DRIVER`?

**Comment by GalBrigitta** [comment]
Well I only use the  file cache driver. Isn't that enough?

**Comment by GalBrigitta** [comment]
Anyway, I've tried to authenticate with postman, and I got a succesfull response with my datas. I have no idea why i got this response with this package. I think I have to write the api calls by myself.

**Comment by upwebdesign** [comment]
@GalBrigitta the reason I ask about the `CACHE_DRIVER` is because the package saves the access token using the cache. If the token is not saved, your API calls will not work. You can verify the token is saved by going to `storage/framework/cache/data`, then keep drilling down to find your cache file. Open it up and see if the `access_token` is stored.

**Comment by GalBrigitta** [comment]
There are two subfolders like b7, 3b. Then a file with a name like 'b73b46d..........' - it is a string. Then in the file:
`1562218970O:8:"stdClass":2:{s:5:"error";s:14:"invalid_client";s:17:"error_description";s:29:"Client authentication failed.";}`

**Comment by GalBrigitta** [comment]
```
$client = new Client();

        $response = $client->request('POST', 'https://api.getgo.com/oauth/v2/token', [
            'headers'     => [
                'Authorization' => 'Basic ' . base64_encode('MYCUSTOMERKEY' . ':' . 'MYCUSTOMERSECRET'),
                'Content-Type'  => 'application/x-www-form-urlencoded'],
            'form_params' => [
                'grant_type' => 'password',
                'username'   => 'MYUSER',
                'password'   => 'MYPASS'
            ]
        ]);
```
So like this is working as well :)

**Comment by GalBrigitta** [comment]
OK. I figured it out, SO:

First of all, with the current version what you get with composer install you get this error:
```
array:2 [
  "state" => "Access object available"
  "accessObject" => {#277 
    +"error": "OAuth API v1 has been decommissioned as announced in February 2018, please switch to OAuth API v2 documented here: https://goto-developer.logmeininc.com/oauth-migration-guide. Please reach out to Support (developer-support@logmein.com) with questions."
  }
]
```
Then I checked what are the changes in the master and I've changed them manually in my project.
For some reason (=my stupidity) I didn't pay attention the added config variable (GOTO_CLIENT_SECRET) which is actually called 'Consumer Secret' on the goto-developer page. GOTO_CONSUMER_SECRET is the user password. For this reason I got confused but at the moment is clear and working.

**Comment by upwebdesign** [comment]
@GalBrigitta glad to hear you got it figured out!
